spring.application.name=backend
spring.profiles.active=local

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/self_healing_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

resilience4j.ratelimiter.instances.apiLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.apiLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.apiLimiter.timeoutDuration=0

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

